config/routes.rb
Rails.application.routes.draw do

  
  get 'sessions/new'

  post 'sessions/create'

  get 'sessions/destroy'
  
  get 'admin', to: 'admin#index'
  
  get 'users/:user_id/gallery', to: 'users#gallery', as: 'gallery'
  
  
  
  get "posts/up_vote/:id", to: "posts#up_vote", as: "up_vote_post"
  
  get "posts/un_vote/:id", to: "posts#un_vote", as: "un_vote_post"
  
  delete 'posts/:post_id/finalize_sale/:folder_id', to: 'posts#finalize_sale', as: 'finalize_sale'
  
  delete 'posts/destroy/:id', to: 'posts#destroy', as: 'destroy_post'
  
  
  
  delete 'articles/destroy/:id', to: 'articles#destroy', as: 'destroy_article'
  
  get 'tabs/:tab_id/articles/new', to: 'articles#new', as: 'new_tab_article'
  
  get 'subtabs/:subtab_id/articles/new', to: 'articles#new', as: 'new_subtab_article'
  
  get 'articles/ad_edit/:id', to: 'articles#ad_edit', as: 'ad_edit'

  get 'articles/approve/:id', to: 'articles#approve', as: 'approve_article'

  get 'articles/deny/:id', to: 'articles#deny', as: 'deny_article'
  
  get 'articles/pending', as: 'pending_articles'
  
  get 'articles/ad_index', as: 'ad_index'
  
  
  
  get 'events/:event_id/going', to: 'events#going', as: 'going'
  
  get 'events/:event_id/not_going', to: 'events#not_going', as: 'not_going'
  
  get 'events/:event_id/attendance', to: 'events#attendance', as: 'attendance'

  get 'events/approve/:id', to: 'events#approve', as: 'approve_event'
  
  get 'subtabs/:subtab_id/events/new', to: 'events#new', as: 'new_subtab_event'
  
  get 'tabs/:tab_id/events/new', to: 'events#new', as: 'new_tab_event'

  get 'events/deny/:id', to: 'events#deny', as: 'deny_event'
  
  get 'events/pending', as: 'pending_events'
  
  
  
  post 'messages/create', as: 'messages'
  
  get 'folders/new/:post_id/:user_id', to: 'folders#new', as: 'inquire'
  
  get 'folders/new/:user_id', to: 'folders#new', as: 'new_folder'
  
  get 'messages/new_messages'
  
  
  
  post 'comments/create', as: 'comments'
  
  get 'comments/show/:id', to: 'comments#show', as: 'comment'
  
  
  
  get 'notes/select', as: "notes_select"
  
  get 'notes/new/:id', to: 'notes#new', as: 'new_note'
  
  get 'notes/new_notes'
  
  
  
  put 'tabs/update'
  
  patch 'subtabs/update/:id', to: 'subtabs#update', as: 'subtab'
  
  post 'subtabs/create', as: 'subtabs'
  
  delete 'tabs/destroy/:id', to: "tabs#destroy", as: 'destroy_tab'

  get 'tabs/approve/:id', to: 'tabs#approve', as: 'approve_tab'

  get 'tabs/deny/:id', to: 'tabs#deny', as: 'deny_tab'

  get 'subtabs/approve/:id', to: 'subtabs#approve', as: 'approve_subtab'

  get 'subtabs/deny/:id', to: 'subtabs#deny', as: 'deny_subtab'
  
  delete 'subtabs/destroy/:id', to: "subtabs#destroy", as: 'destroy_subtab'
  
  get 'tabs/pending', as: 'pending_tabs'
  
  
  
  put 'feedbacks/update'
  
  post 'feedbacks/create', as: 'feedback'
  
  delete 'feedbacks/destroy/:id', to: "feedbacks#destroy", as: 'destroy_feedback'
  
  get 'users/:user_id/feedbacks/new', to: 'feedbacks#new', as: 'new_user_feedback'
  
  get 'posts/:post_id/feedbacks/new', to: 'feedbacks#new', as: 'new_post_feedback'
  
  get 'events/:event_id/feedbacks/new', to: 'feedbacks#new', as: 'new_event_feedback'
  
  get 'articles/:article_id/feedbacks/new', to: 'feedbacks#new', as: 'new_article_feedback'
  
  get 'comments/:comment_id/feedbacks/new', to: 'feedbacks#new', as: 'new_comment_feedback'
  
  get 'tabs/:tab_id/feedbacks/new', to: 'feedbacks#new', as: 'new_tab_feedback'
  
  post 'features/request_invite', as: 'request_invite'
  
  
  
  get 'features/switch_global', as: 'switch_global'
  
  get "features/page_jump/:tab_id", to: 'features#page_jump', as: 'page_jump'
  
  get "features/cherry_pick", to: 'features#cherry_pick', as: 'cherry_pick'
  
  get "features/un_cherry_pick", to: 'features#un_cherry_pick', as: 'un_cherry_pick'
  
  delete 'features/destroy/:id', to: 'features#destroy', as: 'destroy_feature'
  
  get 'features/insert_pre_feature_grid', as: 'insert_pre_feature_grid'
  
  post 'features/create', as: 'features'
  
  
  
  delete 'groups/destroy/:id', to: 'groups#destroy', as: 'destroy_group'
  
  put 'groups/remove_member'
  
  put 'groups/add_member'
  
  put 'groups/remove_zip'
  
  put 'groups/add_zip'
  
  
  
  delete 'codes/destroy/:id', to: 'codes#destroy', as: 'destroy_code'
  
  delete 'game_boards/destroy/:id', to: 'game_boards#destroy', as: 'destroy_board'
  
  get 'game_boards/reset/:id', to: 'game_boards#reset', as: 'reset'
  
  get 'game_boards', to: 'game_boards#index', as: 'boards'
  
  post 'game_boards/create', as: 'game_boards'
  
  post 'cards/create', as: 'cards'
  
  delete 'codes/clear', as: 'clear'
  
  get 'codes/code_data'
  
  
  
  get 'activities/:id/get_location', to: 'activities#get_location', as: 'get_location'
  
  get 'activities/unique_locations', as: 'unique_locations'
  
  get 'activities/unique_visits', as: 'unique_visits'
  
  delete 'activities/destroy_all', as: 'destroy_all_activities'
  
  
  
  put 'translations/update'
  
  delete 'translations/destroy/:id', to: 'translations#destroy', as: 'destroy_translation'
  
  get 'translations/requests', as: 'translation_reqs'
  
  
  
  get "search/search/:query", to: "search#search", as: "tagged"
  
  get "search/search", as: "search"
  
  
  
  get "pages/more", as: "more"
  
  get "pages/back", as: "back"
  
  
  
  post 'tips/create', as: 'tips_create'
  
  
  
  get 'tabs/:tab_id/polls/new', to: 'polls#new', as: 'new_tab_poll'
  
  get 'users/:user_id/polls/new', to: 'polls#new', as: 'new_user_poll'
  
  get 'polls/add_choice/:choice_num', to: 'polls#add_choice', as: 'add_choice'
  
  post 'polls/:poll_id/up_vote/:choice_id', to: 'polls#up_vote', as: 'up_vote_choice'
  
  post 'polls/:poll_id/down_vote/:choice_id', to: 'polls#down_vote', as: 'down_vote_choice'
  
  
  
  get 'tournaments/add_team/:team_num', to: 'tournaments#add_team', as: 'add_team'
  

  root 'welcome#index'
  
  resources :codes
  resources :posts
  resources :banners
  resources :loading_gifs
  resources :translations
  resources :sports_teams
  resources :activities
  resources :feedbacks
  resources :articles
  resources :groups
  resources :events
  resources :notes
  resources :polls
  resources :stats
  
  resources :game_boards do
    resources :cards
  end
  
  resources :folders do
    resources :messages
  end
  
  resources :tabs do
    resources :features
    resources :tournaments
    resources :sports_matches
    resources :subtabs do
      resources :features
    end
  end

  resources :users do
    resources :features
  end
  

end

app/models/note.rb
class Note < ActiveRecord::Base
  belongs_to :user
  validates :message, presence: true
  validate :valid_url
  
  scope :checked, -> { where checked: true }
  scope :unchecked, -> { where checked: false }
  
  def self.notify(sender, receiver, action, item_id=1)
    if sender.present? and receiver.present? and sender != receiver
      if sender
        name = sender.name.capitalize
      else
        sender = User.first
      end
      case action
        when :post_comment
          message = name + " " + Translation.translate("commented on your post.")
        when :article_comment
          message = name + " " + Translation.translate("commented on your article.")
        when :banner_comment
          message = name + " " + Translation.translate("commented on your banner.")
        when :translation_comment
          message = name + " " + Translation.translate("commented on your translation.")
        when :activity_comment
          message = name + " " + Translation.translate("commented on your activity.")
        when :event_comment
          message = name + " " + Translation.translate("commented on your event.")
        when :poll_comment
          message = name + " " + Translation.translate("commented on your poll.")
        when :comment_reply
          message = name + " " + Translation.translate("replied to your comment.")
        when :event_invitation
          message = name + " " + Translation.translate("invited you to their event.")
        when :like_post
          message = name + " " + Translation.translate("liked your post.")
        when :going
          message = name + " " + Translation.translate("RSVPed for your event.")
        when :user_feedback
          message = name + " " + Translation.translate("reviewed your profile.")
        when :mention
          message = name + " " + Translation.translate("mentioned you in a post.")
        when :sales_inquiry
          message = name + " " + Translation.translate("inquired upon your offer.")
        when :sales_reply
          message = name + " " + Translation.translate("replied to your inquiry.")
        when :sale_finalized
          message = name + " " + Translation.translate("finalized the offer.")
        when :message
          message = name + " " + Translation.translate("sent you a message.")
        when :you_won
          message = Translation.translate("You won! Call 555-5454 now!")
        when :event_approved
          message = Translation.translate("Your event was approved.")
        when :event_denied
          message = Translation.translate("Your event was denied.")
        when :tab_approved
          message = Translation.translate("Your tab was approved.")
        when :tab_denied
          message = Translation.translate("Your tab was denied.")
      end
      note = receiver.notes.new(message: message, sender_id: sender.id,
        action: action.to_s, item_id: item_id)
      note.save 
    end
  end
  
  private
  
  def valid_url
    if url.present? and not url.include? "http"
      errors.add(:invalid_url, "Invalid URL. Try prepending http://")
    end
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  def new_notes
    @new_notes = current_user.notes.unchecked.size if current_user
  end
  
  def select
    if master? and session[:group_id]
      zips = []
      Group.find(session[:group_id]).zips.each { |zip| zips << zip.zip_code }
      @notes = Note.where(zip_code: zips).where(action: :admin_message).reverse
      @users = User.where zip_code: zips
    elsif master?
      @users = User.all.sort_by &:name
      @notes = Note.all.reverse
    elsif admin?
      zips = []
      current_user.group.zips.each { |zip| zips << zip.zip_code }
      @notes = Note.where(zip_code: zips).where(action: :admin_message).reverse
      @users = User.where zip_code: zips
    end
    bundle = params[:"/notes/select"]
    user_id = bundle[:user_id] if bundle
    if user_id.present?
      @user = User.find(params[:"/notes/select"][:user_id])
      @note = Note.new(user_id: @user.id)
    end
    log_action("notes_select", (@note ? @note.id : nil))
  end
  
  def new
    @user = User.find_by_name(params[:id])
    @note = Note.new
    log_action("notes_new")
  end
  
  def create
    @user = User.find_by_name(params[:user_name])
    @note = @user.notes.new(params[:note].permit(:message, :url))
    @note.sender_id = current_user.id
    @note.action = params[:note_action].to_s
    @note.zip_code = @user.zip_code
    @note.item_id = 1
    
    if @note.save
      flash[:notice] = translate("The notification was sent.")
      log_action("notes_create", @note.id)
      redirect_to user_path(@user.name)
    elsif @note.errors.include? :invalid_url
      flash[:error] = translate(@note.errors[:invalid_url].first)
      redirect_to :back
    else
      flash[:error] = translate("Invalid input.")
      log_action("notes_create_fail")
      redirect_to :back
    end
  end
  
  def index
    if current_user then
      reset_page
      @all_items = current_user.notes
      @all_items.each do |note|
        note.update checked: true
      end
      @items = paginate @all_items
      @notes_shown = true
    end
    @advert = Article.local_advert(current_user)
    log_action("notes_index")
  end
  
  def clear
    @notes = current_user.notes
    @notes.each do |note|
      note.destroy!
    end
    log_action("notes_clear")
    redirect_to user_notes_path(current_user.name)
  end
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/_card.html.erb
<!-- notes -->

<div id="card">
	<div align="center" id="notes_card">
		<%= render "notes/time_ago", note: note %>
		<% case note.action.to_sym %>
			<% when :post_comment %>
				<p><%= link_to note.message, post_path(note.item_id) %></p>
				
			<% when :article_comment %>
				<p><%= link_to note.message, article_path(note.item_id) %></p>
				
			<% when :event_comment %>
				<p><%= link_to note.message, event_path(note.item_id) %></p>
				
			<% when :banner_comment %>
				<p><%= link_to note.message, banner_path(note.item_id) %></p>
				
			<% when :translation_comment %>
				<p><%= link_to note.message, translation_path(note.item_id) %></p>
				
			<% when :activity_comment %>
				<p><%= link_to note.message, activity_path(note.item_id) %></p>
				
			<% when :poll_comment %>
				<p><%= link_to note.message, poll_path(note.item_id) %></p>
				
			<% when :comment_reply %>
				<p><%= link_to note.message, comment_path(note.item_id) %></p>
				
			<% when :like_post %>
				<p><%= link_to note.message, post_path(note.item_id) %></p>
				
			<% when :event_approved %>
				<p><%= link_to note.message, event_path(note.item_id) %></p>
				
			<% when :event_denied %>
				<p><%= link_to note.message, event_path(note.item_id) %></p>
				
			<% when :tab_approved %>
				<p><%= link_to note.message, tab_path(note.item_id) %></p>
				
			<% when :tab_denied %>
				<p><%= link_to note.message, tab_path(note.item_id) %></p>
			
			<% when :user_feedback %>
				<p><%= link_to note.message, feedbacks_path %></p>
				
			<% when :admin_message %>
				<p><%= link_to note.message, (note.url.present? ? note.url : notes_path) %></p>
				
			<% when :you_won %>
				<p><%= link_to note.message, notes_path %></p>
				
			<% when :sales_inquiry, :sales_reply %>
				<p><%= link_to note.message, folder_path(note.item_id) %></p>
				
			<% when :sale_finalized %>
				<p><%= link_to note.message, user_path(User.find_by_id(note.sender_id).name) %></p>
				
			<% when :message %>
				<p><%= link_to note.message, folder_path(note.item_id) %></p>
				
			<% when :mention %>
				<p><%= link_to note.message, post_path(note.item_id) %></p>
				
			<% when :event_invitation %>
				<p><%= link_to note.message, event_path(note.item_id) %></p>
				
			<% when :going %>
				<p><%= link_to note.message, event_path(note.item_id) %></p>
		<% end %>
	</div>
</div>

app/views/notes/_feed.html.erb
<!-- notes -->

<% @items.each do |note| %>
	<%= render "notes/card", note: note %>
<% end %>

<% unless @items.size < page_size %>
	<div id="more_content_anchor"></div>
<% end %>

app/views/notes/_nav_li.html.erb
<!-- notes -->

<li id="notes_nav_li">
	<%= link_to notes_path, title: translate("View your notifications") do %>
		<div><%= translate("Notes") %> <span class="badge">
			<%= @new_notes %>
		</span></div>
	<% end %>
</li>

app/views/notes/_new.html.erb
<!-- notes -->

<div id="card">
	<% if @user %>
		<p><%= translate("Send a notification to") %><%= " " + @user.name.capitalize %></p>
	<% end %>
	
	<%= form_for @note, :html => {:multipart => true, "data-ajax" => false} do |f| %>
		<%= hidden_field_tag :user_name, (@user ? @user.name : params[:id]) %>
		<%= hidden_field_tag :note_action, :admin_message %>
		<p>
			<%= f.text_field :message, placeholder: translate("Message"), class: "form-control" %>
		</p>
		<p>
			<%= f.text_field :url, placeholder: translate("URL (optional)"), class: "form-control" %>
		</p>
		<%= f.submit translate("Submit"), class: "btn btn-default btn-lg btn-block" %>
	<% end %>
</div>

app/views/notes/_notify_button.html.erb
<% if privileged? and current_user != @user %>
	<%= link_to translate("Notify"), new_note_path(@user.name),
		title: translate("Notify this user with a message or link"), class: :card_link %>
<% end %>

app/views/notes/_time_ago.html.erb
<!-- notes -->

<% time_ago = time_ago_in_words(note.created_at) + " ago" %>
<% if time_ago.include? "about" %>
	<% time_ago.slice! "about " %>
<% end %>

<%= link_to time_ago, notes_path, class: :top_left_link %>

app/views/notes/index.html.erb
<!-- notes -->

<% if current_user %>
	<% if current_user.notes.empty? %>
		<div id="card"><div align="center">
			<%= translate "You have zero notifications." %>
		</div></div>
	<% end %>

	<%= render "notes/feed" %>
	
	<%= render "loading_gifs/loading_footer", items: @items, all_items: @all_items %>
<% end %>

app/views/notes/new.html.erb
<%= render "notes/new" %>

app/views/notes/new_notes.js.erb
<% if @new_notes and @new_notes > 0 %>
	$("#notes_nav_li").replaceWith(<%=j render "notes/nav_li" %>);
<% end %>

app/views/notes/notify.html.erb
<%= render "notes/new" %>

app/views/notes/select.html.erb
<% if current_user and current_user.admin %>
	<% if @note %>
		<%= render "notes/new" %>
	<% end %>
	
	<div id="card">
		<%= form_for notes_select_path, :method => "get" do |f| %>
			<% options = [[translate("Choose a user to notify"), nil]] %>
			<% @users.each { |user| options << [user.name, user.id] } %>
			<p><%= f.select :user_id, options_for_select(options), {}, class: "form-control" %></p>
			<%= f.submit "Select", class: "btn btn-default btn-lg btn-block" %>
		<% end %>
	</div>
<% end %>

<% for note in @notes %>
	<%= render "notes/card", note: note %>
<% end %>

</br>