config/routes.rb
Rails.application.routes.draw do

  
  get 'sessions/new'

  post 'sessions/create'

  get 'sessions/destroy'
  
  get 'admin', to: 'admin#index'
  
  get 'users/:user_id/gallery', to: 'users#gallery', as: 'gallery'
  
  
  
  get "posts/up_vote/:id", to: "posts#up_vote", as: "up_vote_post"
  
  get "posts/un_vote/:id", to: "posts#un_vote", as: "un_vote_post"
  
  delete 'posts/:post_id/finalize_sale/:folder_id', to: 'posts#finalize_sale', as: 'finalize_sale'
  
  delete 'posts/destroy/:id', to: 'posts#destroy', as: 'destroy_post'
  
  
  
  delete 'articles/destroy/:id', to: 'articles#destroy', as: 'destroy_article'
  
  get 'tabs/:tab_id/articles/new', to: 'articles#new', as: 'new_tab_article'
  
  get 'subtabs/:subtab_id/articles/new', to: 'articles#new', as: 'new_subtab_article'
  
  get 'articles/ad_edit/:id', to: 'articles#ad_edit', as: 'ad_edit'

  get 'articles/approve/:id', to: 'articles#approve', as: 'approve_article'

  get 'articles/deny/:id', to: 'articles#deny', as: 'deny_article'
  
  get 'articles/pending', as: 'pending_articles'
  
  get 'articles/ad_index', as: 'ad_index'
  
  
  
  get 'events/:event_id/going', to: 'events#going', as: 'going'
  
  get 'events/:event_id/not_going', to: 'events#not_going', as: 'not_going'
  
  get 'events/:event_id/attendance', to: 'events#attendance', as: 'attendance'

  get 'events/approve/:id', to: 'events#approve', as: 'approve_event'
  
  get 'subtabs/:subtab_id/events/new', to: 'events#new', as: 'new_subtab_event'
  
  get 'tabs/:tab_id/events/new', to: 'events#new', as: 'new_tab_event'

  get 'events/deny/:id', to: 'events#deny', as: 'deny_event'
  
  get 'events/pending', as: 'pending_events'
  
  
  
  post 'messages/create', as: 'messages'
  
  get 'folders/new/:post_id/:user_id', to: 'folders#new', as: 'inquire'
  
  get 'folders/new/:user_id', to: 'folders#new', as: 'new_folder'
  
  get 'messages/new_messages'
  
  
  
  post 'comments/create', as: 'comments'
  
  get 'comments/show/:id', to: 'comments#show', as: 'comment'
  
  
  
  get 'notes/select', as: "notes_select"
  
  get 'notes/new/:id', to: 'notes#new', as: 'new_note'
  
  get 'notes/new_notes'
  
  
  
  put 'tabs/update'
  
  patch 'subtabs/update/:id', to: 'subtabs#update', as: 'subtab'
  
  post 'subtabs/create', as: 'subtabs'
  
  delete 'tabs/destroy/:id', to: "tabs#destroy", as: 'destroy_tab'

  get 'tabs/approve/:id', to: 'tabs#approve', as: 'approve_tab'

  get 'tabs/deny/:id', to: 'tabs#deny', as: 'deny_tab'

  get 'subtabs/approve/:id', to: 'subtabs#approve', as: 'approve_subtab'

  get 'subtabs/deny/:id', to: 'subtabs#deny', as: 'deny_subtab'
  
  delete 'subtabs/destroy/:id', to: "subtabs#destroy", as: 'destroy_subtab'
  
  get 'tabs/pending', as: 'pending_tabs'
  
  
  
  put 'feedbacks/update'
  
  post 'feedbacks/create', as: 'feedback'
  
  delete 'feedbacks/destroy/:id', to: "feedbacks#destroy", as: 'destroy_feedback'
  
  get 'users/:user_id/feedbacks/new', to: 'feedbacks#new', as: 'new_user_feedback'
  
  get 'posts/:post_id/feedbacks/new', to: 'feedbacks#new', as: 'new_post_feedback'
  
  get 'events/:event_id/feedbacks/new', to: 'feedbacks#new', as: 'new_event_feedback'
  
  get 'articles/:article_id/feedbacks/new', to: 'feedbacks#new', as: 'new_article_feedback'
  
  get 'comments/:comment_id/feedbacks/new', to: 'feedbacks#new', as: 'new_comment_feedback'
  
  get 'tabs/:tab_id/feedbacks/new', to: 'feedbacks#new', as: 'new_tab_feedback'
  
  post 'features/request_invite', as: 'request_invite'
  
  
  
  get 'features/switch_global', as: 'switch_global'
  
  get "features/page_jump/:tab_id", to: 'features#page_jump', as: 'page_jump'
  
  get "features/cherry_pick", to: 'features#cherry_pick', as: 'cherry_pick'
  
  get "features/un_cherry_pick", to: 'features#un_cherry_pick', as: 'un_cherry_pick'
  
  delete 'features/destroy/:id', to: 'features#destroy', as: 'destroy_feature'
  
  get 'features/insert_pre_feature_grid', as: 'insert_pre_feature_grid'
  
  post 'features/create', as: 'features'
  
  
  
  delete 'groups/destroy/:id', to: 'groups#destroy', as: 'destroy_group'
  
  put 'groups/remove_member'
  
  put 'groups/add_member'
  
  put 'groups/remove_zip'
  
  put 'groups/add_zip'
  
  
  
  delete 'codes/destroy/:id', to: 'codes#destroy', as: 'destroy_code'
  
  delete 'game_boards/destroy/:id', to: 'game_boards#destroy', as: 'destroy_board'
  
  get 'game_boards/reset/:id', to: 'game_boards#reset', as: 'reset'
  
  get 'game_boards', to: 'game_boards#index', as: 'boards'
  
  post 'game_boards/create', as: 'game_boards'
  
  post 'cards/create', as: 'cards'
  
  delete 'codes/clear', as: 'clear'
  
  get 'codes/code_data'
  
  
  
  get 'activities/:id/get_location', to: 'activities#get_location', as: 'get_location'
  
  get 'activities/unique_locations', as: 'unique_locations'
  
  get 'activities/unique_visits', as: 'unique_visits'
  
  delete 'activities/destroy_all', as: 'destroy_all_activities'
  
  
  
  put 'translations/update'
  
  delete 'translations/destroy/:id', to: 'translations#destroy', as: 'destroy_translation'
  
  get 'translations/requests', as: 'translation_reqs'
  
  
  
  get "search/search/:query", to: "search#search", as: "tagged"
  
  get "search/search", as: "search"
  
  
  
  get "pages/more", as: "more"
  
  get "pages/back", as: "back"
  
  
  
  post 'tips/create', as: 'tips_create'
  
  
  
  get 'tabs/:tab_id/polls/new', to: 'polls#new', as: 'new_tab_poll'
  
  get 'users/:user_id/polls/new', to: 'polls#new', as: 'new_user_poll'
  
  get 'polls/add_choice/:choice_num', to: 'polls#add_choice', as: 'add_choice'
  
  post 'polls/:poll_id/up_vote/:choice_id', to: 'polls#up_vote', as: 'up_vote_choice'
  
  post 'polls/:poll_id/down_vote/:choice_id', to: 'polls#down_vote', as: 'down_vote_choice'
  
  
  
  get 'tournaments/add_team/:team_num', to: 'tournaments#add_team', as: 'add_team'
  

  root 'welcome#index'
  
  resources :codes
  resources :posts
  resources :banners
  resources :loading_gifs
  resources :translations
  resources :sports_teams
  resources :activities
  resources :feedbacks
  resources :articles
  resources :groups
  resources :events
  resources :notes
  resources :polls
  resources :stats
  
  resources :game_boards do
    resources :cards
  end
  
  resources :folders do
    resources :messages
  end
  
  resources :tabs do
    resources :features
    resources :tournaments
    resources :sports_matches
    resources :subtabs do
      resources :features
    end
  end

  resources :users do
    resources :features
  end
  

end

app/models/translation.rb
class Translation < ActiveRecord::Base
  belongs_to :post
  belongs_to :event
  belongs_to :article
  belongs_to :subtab
  belongs_to :user
  belongs_to :tab
  
  has_many :comments
  
  validate :spanish_or_english

	def self.language(text)
		wl = WhatLanguage.new(:english, :spanish)
		return wl.language(text)
	end
	
	def self.translator
    return BingTranslator.new('EFW-1993',
      ENV['BING_TRANSLATOR_CLIENT_SECRET'])
	end
  
  def self.auto_translate text
    if language(text).eql? :english
      translator.translate(text, :from => 'en', :to => 'es')
    elsif language(text).eql? :spanish
      translator.translate(text, :from => 'es', :to => 'en')
    else
    	text
    end
  end
  
  def self.translate(english)
    spanish = self.site_english(english)
    return spanish.present? ? spanish.last.spanish : english
  end
  
  def self.requests
    _requests = []
    where(english: [nil, ""]).each { |_request| _requests << _request }
    where(spanish: [nil, ""]).each { |_request| _requests << _request }
    return _requests.sort_by(&:id)
  end
  
  def self.translated
    _translated = []
    for _translation in self.all
      if _translation.english.present? and _translation.spanish.present?
        _translated << _translation
      end
    end
    return _translated
  end
  
  def self.translate_to_english(spanish)
    english = self.site_spanish(spanish)
    return english.present? ? english.last.english : spanish
  end
  
  # site translations are not tied to any model but
  # to the site itself through links and buttons or other labels
  
  def self.site_spanish(_spanish)
    _site_spanish = []
    for _translation in self.site
      if _translation.spanish == _spanish
        _site_spanish << _translation
      end
    end
    return _site_spanish
  end
  
  def self.site_english(_english)
    _site_english = []
    for _translation in self.site
      if _translation.english == _english
        _site_english << _translation
      end
    end
    return _site_english
  end
  
  def self.site
    translations = []
    for translation in self.
      where(tab_id: nil).
      where(post_id: nil).
      where(event_id: nil).
      where(subtab_id: nil).
      where(article_id: nil)
      translations << translation
    end
    return translations
  end
  
  private
  
  def spanish_or_english
    if (request.nil? and (spanish.nil? or english.nil?)) or (request and spanish.nil? and english.nil?)
      errors.add(:no_spanish_or_english, "Invalid input.")
    end
  end
end

app/controllers/translations_controller.rb
class TranslationsController < ApplicationController
  def requests
    reset_page
    @requests = paginate Translation.requests.reverse
    log_action("translations_requests")
  end
  
  def show
    @translation = Translation.find_by_id(params[:id])
    if @translation
      @comments = @translation.comments
      @new_comment = Comment.new
      log_action("translations_show")
    else
      log_action("translations_show_fail")
    end
  end
  
  def index
    reset_page
    @translation = Translation.new
    @translations = paginate Translation.translated
    log_action("translations_index")
  end
  
  def edit
    @translation = Translation.find(params[:id])
    log_action("translations_edit", @translation.id)
  end
  
  def update
    @translation = Translation.find(params[:id])
    @translation.user_id = params[:user_id]
    if @translation.update(params[:translation].permit(:english, :spanish))
      flash[:notice] = translate("The translation was successfully updated.")
      log_action("translations_update", @translation.id)
      redirect_to translations_path
    else
      flash[:error] = translate("Invalid input.")
      log_action("translations_update_fail", @translation.id)
      redirect_to :back
    end
  end
  
  def create
    @translation = Translation.new(params[:translation].permit(:english, :spanish, :request))
    @translation.user_id = params[:user_id]
    @translation.request = true \
      if @translation.english.empty? or @translation.spanish.empty?
    if @translation.save
      flash[:notice] = translate("Translation saved successfully.")
      log_action("translations_create", @translation.id)
    else
      flash[:error] = translate("Translation could not be saved.")
      log_action("translations_create_fail")
    end
    redirect_to :back
  end
  
  def destroy
    @translation = Translation.find_by_id(params[:id])
    if @translation.destroy
      flash[:notice] = translate("Translation successfully deleted.")
      log_action("translations_destroy")
      redirect_to translations_path
    else
      flash[:error] = translate("Translation could not be deleted.")
      log_action("translations_destroy_fail", @translation.id)
      redirect_to :back
    end
  end
end

app/helpers/translations_helper.rb
module TranslationsHelper
	def auto_translate text
		t = Translation
    if t.language(text).eql? :english and not english?
      t.translator.translate(text, :from => 'en', :to => 'es')
    elsif t.language(text).eql? :spanish and english?
      t.translator.translate(text, :from => 'es', :to => 'en')
    else
    	text
    end
	end
end

app/views/translations/_card.html.erb
<!-- translations -->

<div id="card">
	<%= render "translations/card_links", translation: translation %>
	
	<div align="center" id="translation_content_body">
		<p>
			<strong><%= translate("English:") %></strong> <%= translation.english %>
		</p>
		<div>
			<strong><%= translate("Spanish:") %></strong> <%= translation.spanish %>
		</div>
	</div>
</div>

app/views/translations/_card_links.html.erb
<!-- translations -->

<% _time_ago = time_ago(time_ago_in_words(translation.created_at)) %>
<%= link_to _time_ago, translation_path(translation), class: :top_left_link %>

<% if translation.user_id.present? %>
	<%= link_to translate("Translated by") + " " + translation.user.name.capitalize,
		user_path(translation.user.name), class: :top_right_link %>
<% end %>

<% unless translation.comments.empty? %>
	<%= link_to translate("Comment") + " #{translation.comments.size}", translation_path(translation),
		title: translate("Leave a comment"), class: :bottom_right_link %>
<% else %>
	<%= link_to translate("Comment"), translation_path(translation),
		title: translate("Leave a comment"), class: :bottom_right_link %>
<% end %>

<table class="bottom_left_link_table">
	<tr>
		<td class="link_table_spacing">
			<%= link_to translate("Edit"), edit_translation_path(translation), class: :card_link %>
		</td>
		<td>
			<%= link_to translate("Delete"), destroy_translation_path(translation), method: :delete, data: {
				confirm: translate('Are you sure you want to delete this translation?') },
				title: translate("Permanently delete this translation"), class: :card_link %>
		</td>
	</tr>
</table>

app/views/translations/_new.html.erb
<div id="card">
	<p><%= translate("Enter translations for the site") %></p>
	<%= form_for @translation do |f| %>
		<%= hidden_field_tag :user_id, current_user.id %>
		<p>
			<%= f.text_area :english, placeholder: translate("English"), class: "form-control" %>
		</p>
		<p>
			<%= f.text_area :spanish, placeholder: translate("Spanish"), class: "form-control" %>
		</p>
		<p class="form-control">
			<%= f.label translate("Request translation") %>
			<%= f.check_box :request %>
		</p>
		<p>
			<%= f.submit translate("Submit"), class: "btn btn-default btn-lg btn-block" %>
		</p>
	<% end %>
</div>

app/views/translations/edit.html.erb
<div id="card">
<%= form_for @translation, url: translation_path(@translation), method: :patch do |f| %>
	<%= hidden_field_tag :id, @translation.id %>
	<p>
		<%= f.text_field :english, class: "form-control" %>
	</p>
	<p>
		<%= f.text_field :spanish, class: "form-control" %>
	</p>
	<p>
		<%= f.submit translate("Update"), class: "btn btn-default btn-lg btn-block" %>
	</p>
<% end %>
</div>

app/views/translations/index.html.erb
<!-- translations -->

<% if privileged? %>
	<div id="large_button">
		<%= link_to translate("Translation requests"), translation_reqs_path, class: "btn btn-default btn-lg btn-block" %>
	</div></br>

	<%= render "translations/new" %>

	<% for translation in @translations %>
		<%= render "translations/card", translation: translation %>
	<% end %>

	<%= render "pages/more_back", all_items: Translation.translated, items: @translations %>
<% end %>

app/views/translations/new.html.erb
<div id="card">
	<p><%= translate("Enter translations for the site") %></p>
	<%= form_for @translation do |f| %>
		<p>
			<%= f.text_field :english, placeholder: translate("English"), class: "form-control" %>
		</p>
		<p>
			<%= f.text_field :spanish, placeholder: translate("Spanish"), class: "form-control" %>
		</p>
		<p>
			<%= f.submit translate("Submit"), class: "btn btn-default btn-lg btn-block" %>
		</p>
	<% end %>
</div>

app/views/translations/requests.html.erb
<!-- translations -->

<% if @requests.empty? %>
	<div id="card">
		<div align="center">
			<%= translate("There aren't any translation requests right now.")%>
		</div>
	</div>
<% else %>
	<% for request in @requests %>
		<div id="card">
			<%= form_for request, url: translation_path(request), method: :put do |f| %>
				<%= hidden_field_tag :user_id, current_user.id %>
				<%= hidden_field_tag :requested, false %>
				<%= hidden_field_tag :id, request.id %>
				<p>
					<%= f.text_area :english, placeholder: translate("English"), class: "form-control" %>
				</p>
				<p>
					<%= f.text_area :spanish, placeholder: translate("Spanish"), class: "form-control" %>
				</p>
				<div>
					<%= f.submit translate("Translate"), class: "btn btn-default btn-lg btn-block" %>
				</div>
			<% end %>
		</div>
	<% end %>

	<%= render "pages/more_back", all_items: Translation.requests, items: @requests %>
<% end %>

</br>

app/views/translations/show.html.erb
<!-- translations -->

<%= render "translations/card", translation: @translation %>

<% @comments.each do |comment| %>
	<%= render "comments/card", comment: comment %>
<% end %>

<%= render "comments/new" if current_user %>