config/routes.rb
Rails.application.routes.draw do

  
  get 'sessions/new'

  post 'sessions/create'

  get 'sessions/destroy'
  
  get 'admin', to: 'admin#index'
  
  get 'users/:user_id/gallery', to: 'users#gallery', as: 'gallery'
  
  
  
  get "posts/up_vote/:id", to: "posts#up_vote", as: "up_vote_post"
  
  get "posts/un_vote/:id", to: "posts#un_vote", as: "un_vote_post"
  
  delete 'posts/:post_id/finalize_sale/:folder_id', to: 'posts#finalize_sale', as: 'finalize_sale'
  
  delete 'posts/destroy/:id', to: 'posts#destroy', as: 'destroy_post'
  
  
  
  delete 'articles/destroy/:id', to: 'articles#destroy', as: 'destroy_article'
  
  get 'tabs/:tab_id/articles/new', to: 'articles#new', as: 'new_tab_article'
  
  get 'subtabs/:subtab_id/articles/new', to: 'articles#new', as: 'new_subtab_article'
  
  get 'articles/ad_edit/:id', to: 'articles#ad_edit', as: 'ad_edit'

  get 'articles/approve/:id', to: 'articles#approve', as: 'approve_article'

  get 'articles/deny/:id', to: 'articles#deny', as: 'deny_article'
  
  get 'articles/pending', as: 'pending_articles'
  
  get 'articles/ad_index', as: 'ad_index'
  
  
  
  get 'events/:event_id/going', to: 'events#going', as: 'going'
  
  get 'events/:event_id/not_going', to: 'events#not_going', as: 'not_going'
  
  get 'events/:event_id/attendance', to: 'events#attendance', as: 'attendance'

  get 'events/approve/:id', to: 'events#approve', as: 'approve_event'
  
  get 'subtabs/:subtab_id/events/new', to: 'events#new', as: 'new_subtab_event'
  
  get 'tabs/:tab_id/events/new', to: 'events#new', as: 'new_tab_event'

  get 'events/deny/:id', to: 'events#deny', as: 'deny_event'
  
  get 'events/pending', as: 'pending_events'
  
  
  
  post 'messages/create', as: 'messages'
  
  get 'folders/new/:post_id/:user_id', to: 'folders#new', as: 'inquire'
  
  get 'folders/new/:user_id', to: 'folders#new', as: 'new_folder'
  
  get 'messages/new_messages'
  
  
  
  post 'comments/create', as: 'comments'
  
  get 'comments/show/:id', to: 'comments#show', as: 'comment'
  
  
  
  get 'notes/select', as: "notes_select"
  
  get 'notes/new/:id', to: 'notes#new', as: 'new_note'
  
  get 'notes/new_notes'
  
  
  
  put 'tabs/update'
  
  patch 'subtabs/update/:id', to: 'subtabs#update', as: 'subtab'
  
  post 'subtabs/create', as: 'subtabs'
  
  delete 'tabs/destroy/:id', to: "tabs#destroy", as: 'destroy_tab'

  get 'tabs/approve/:id', to: 'tabs#approve', as: 'approve_tab'

  get 'tabs/deny/:id', to: 'tabs#deny', as: 'deny_tab'

  get 'subtabs/approve/:id', to: 'subtabs#approve', as: 'approve_subtab'

  get 'subtabs/deny/:id', to: 'subtabs#deny', as: 'deny_subtab'
  
  delete 'subtabs/destroy/:id', to: "subtabs#destroy", as: 'destroy_subtab'
  
  get 'tabs/pending', as: 'pending_tabs'
  
  
  
  put 'feedbacks/update'
  
  post 'feedbacks/create', as: 'feedback'
  
  delete 'feedbacks/destroy/:id', to: "feedbacks#destroy", as: 'destroy_feedback'
  
  get 'users/:user_id/feedbacks/new', to: 'feedbacks#new', as: 'new_user_feedback'
  
  get 'posts/:post_id/feedbacks/new', to: 'feedbacks#new', as: 'new_post_feedback'
  
  get 'events/:event_id/feedbacks/new', to: 'feedbacks#new', as: 'new_event_feedback'
  
  get 'articles/:article_id/feedbacks/new', to: 'feedbacks#new', as: 'new_article_feedback'
  
  get 'comments/:comment_id/feedbacks/new', to: 'feedbacks#new', as: 'new_comment_feedback'
  
  get 'tabs/:tab_id/feedbacks/new', to: 'feedbacks#new', as: 'new_tab_feedback'
  
  post 'features/request_invite', as: 'request_invite'
  
  
  
  get 'features/switch_global', as: 'switch_global'
  
  get "features/page_jump/:tab_id", to: 'features#page_jump', as: 'page_jump'
  
  get "features/cherry_pick", to: 'features#cherry_pick', as: 'cherry_pick'
  
  get "features/un_cherry_pick", to: 'features#un_cherry_pick', as: 'un_cherry_pick'
  
  delete 'features/destroy/:id', to: 'features#destroy', as: 'destroy_feature'
  
  get 'features/insert_pre_feature_grid', as: 'insert_pre_feature_grid'
  
  post 'features/create', as: 'features'
  
  
  
  delete 'groups/destroy/:id', to: 'groups#destroy', as: 'destroy_group'
  
  put 'groups/remove_member'
  
  put 'groups/add_member'
  
  put 'groups/remove_zip'
  
  put 'groups/add_zip'
  
  
  
  delete 'codes/destroy/:id', to: 'codes#destroy', as: 'destroy_code'
  
  delete 'game_boards/destroy/:id', to: 'game_boards#destroy', as: 'destroy_board'
  
  get 'game_boards/reset/:id', to: 'game_boards#reset', as: 'reset'
  
  get 'game_boards', to: 'game_boards#index', as: 'boards'
  
  post 'game_boards/create', as: 'game_boards'
  
  post 'cards/create', as: 'cards'
  
  delete 'codes/clear', as: 'clear'
  
  get 'codes/code_data'
  
  
  
  get 'activities/:id/get_location', to: 'activities#get_location', as: 'get_location'
  
  get 'activities/unique_locations', as: 'unique_locations'
  
  get 'activities/unique_visits', as: 'unique_visits'
  
  delete 'activities/destroy_all', as: 'destroy_all_activities'
  
  
  
  put 'translations/update'
  
  delete 'translations/destroy/:id', to: 'translations#destroy', as: 'destroy_translation'
  
  get 'translations/requests', as: 'translation_reqs'
  
  
  
  get "search/search/:query", to: "search#search", as: "tagged"
  
  get "search/search", as: "search"
  
  
  
  get "pages/more", as: "more"
  
  get "pages/back", as: "back"
  
  
  
  post 'tips/create', as: 'tips_create'
  
  
  
  get 'tabs/:tab_id/polls/new', to: 'polls#new', as: 'new_tab_poll'
  
  get 'users/:user_id/polls/new', to: 'polls#new', as: 'new_user_poll'
  
  get 'polls/add_choice/:choice_num', to: 'polls#add_choice', as: 'add_choice'
  
  post 'polls/:poll_id/up_vote/:choice_id', to: 'polls#up_vote', as: 'up_vote_choice'
  
  post 'polls/:poll_id/down_vote/:choice_id', to: 'polls#down_vote', as: 'down_vote_choice'
  
  
  
  get 'tournaments/add_team/:team_num', to: 'tournaments#add_team', as: 'add_team'
  

  root 'welcome#index'
  
  resources :codes
  resources :posts
  resources :banners
  resources :loading_gifs
  resources :translations
  resources :sports_teams
  resources :activities
  resources :feedbacks
  resources :articles
  resources :groups
  resources :events
  resources :notes
  resources :polls
  resources :stats
  
  resources :game_boards do
    resources :cards
  end
  
  resources :folders do
    resources :messages
  end
  
  resources :tabs do
    resources :features
    resources :tournaments
    resources :sports_matches
    resources :subtabs do
      resources :features
    end
  end

  resources :users do
    resources :features
  end
  

end

app/views/admin/_admin_buttons.html.erb
<!-- admins -->

<%= link_to translate("News"), new_article_path, class: "btn btn-default btn-lg btn-block",
	id: "admin_button", title: translate("Write articles for your area") %>
	
<%= link_to translate("Notes"), notes_select_path, class: "btn btn-default btn-lg btn-block",
	id: "admin_button", title: translate("Notify users with messages or links") %>
	
<%= link_to translate("Events"), pending_events_path, class: "btn btn-default btn-lg btn-block",
	id: "admin_button", title: translate("Approve, deny, or plan events") %>

app/views/admin/_master_buttons.html.erb
<!-- admin -->

<%= link_to translate("Groups"), groups_path, class: "btn btn-default btn-lg btn-block",
	id: "admin_button", title: translate("Manage groups by adding or removing admins or zip codes") %>

<%= link_to translate("Translate"), translations_path, class: "btn btn-default btn-lg btn-block",
	id: "admin_button", title: translate("Manage translation requests or site translations") %>
	
<%= link_to translate("Loading"), loading_gifs_path, class: "btn btn-default btn-lg btn-block",
	id: "admin_button", title: translate("Upload loading gifs to display in feeds") %>

<%= link_to translate("Adverts"), ad_index_path, class: "btn btn-default btn-lg btn-block",
	id: "admin_button", title: translate("Upload advertisements and check view counts") %>

<%= link_to translate("Banner"), banners_path, class: "btn btn-default btn-lg btn-block",
	id: "admin_button", title: translate("Upload banners for the homepage") %>

<%= link_to translate("Codes"), codes_path, class: "btn btn-default btn-lg btn-block",
	id: "admin_button", title: translate("Manage codes for cards, gameboards, and prizes") %>

<%= link_to translate("Data"), activities_path, class: "btn btn-default btn-lg btn-block",
	id: "admin_button", title: translate("Track user behavior and statistics") %>

<%= link_to translate("Tabs"), pending_tabs_path, class: "btn btn-default btn-lg btn-block",
	id: "admin_button", title: translate("Approve, deny, or manage social media tabs") %>

app/views/admin/index.html.erb
<% if privileged? %>
	<div id="card">
		<div align="center">
			<%= translate("Welcome, " + (master? ? "Master" : "Administrator")) + " " + current_user.name.capitalize %>
		</div>
	</div>
	
	<div id="card">
		<% if master? %>
			<%= render "admin/master_buttons" %>
		<% end %>
		<%= render "admin/admin_buttons" %>
	</div></br>
<% else %>
	<div id="card">
		<div align="center"><%= translate "Check your privilege." %></div>
	</div>
<% end %>