config/routes.rb
Rails.application.routes.draw do

  
  get 'sessions/new'

  post 'sessions/create'

  get 'sessions/destroy'
  
  get 'admin', to: 'admin#index'
  
  get 'users/:user_id/gallery', to: 'users#gallery', as: 'gallery'
  
  
  
  get "posts/up_vote/:id", to: "posts#up_vote", as: "up_vote_post"
  
  get "posts/un_vote/:id", to: "posts#un_vote", as: "un_vote_post"
  
  delete 'posts/:post_id/finalize_sale/:folder_id', to: 'posts#finalize_sale', as: 'finalize_sale'
  
  delete 'posts/destroy/:id', to: 'posts#destroy', as: 'destroy_post'
  
  
  
  delete 'articles/destroy/:id', to: 'articles#destroy', as: 'destroy_article'
  
  get 'tabs/:tab_id/articles/new', to: 'articles#new', as: 'new_tab_article'
  
  get 'subtabs/:subtab_id/articles/new', to: 'articles#new', as: 'new_subtab_article'
  
  get 'articles/ad_edit/:id', to: 'articles#ad_edit', as: 'ad_edit'

  get 'articles/approve/:id', to: 'articles#approve', as: 'approve_article'

  get 'articles/deny/:id', to: 'articles#deny', as: 'deny_article'
  
  get 'articles/pending', as: 'pending_articles'
  
  get 'articles/ad_index', as: 'ad_index'
  
  
  
  get 'events/:event_id/going', to: 'events#going', as: 'going'
  
  get 'events/:event_id/not_going', to: 'events#not_going', as: 'not_going'
  
  get 'events/:event_id/attendance', to: 'events#attendance', as: 'attendance'

  get 'events/approve/:id', to: 'events#approve', as: 'approve_event'
  
  get 'subtabs/:subtab_id/events/new', to: 'events#new', as: 'new_subtab_event'
  
  get 'tabs/:tab_id/events/new', to: 'events#new', as: 'new_tab_event'

  get 'events/deny/:id', to: 'events#deny', as: 'deny_event'
  
  get 'events/pending', as: 'pending_events'
  
  
  
  post 'messages/create', as: 'messages'
  
  get 'folders/new/:post_id/:user_id', to: 'folders#new', as: 'inquire'
  
  get 'folders/new/:user_id', to: 'folders#new', as: 'new_folder'
  
  get 'messages/new_messages'
  
  
  
  post 'comments/create', as: 'comments'
  
  get 'comments/show/:id', to: 'comments#show', as: 'comment'
  
  
  
  get 'notes/select', as: "notes_select"
  
  get 'notes/new/:id', to: 'notes#new', as: 'new_note'
  
  get 'notes/new_notes'
  
  
  
  put 'tabs/update'
  
  patch 'subtabs/update/:id', to: 'subtabs#update', as: 'subtab'
  
  post 'subtabs/create', as: 'subtabs'
  
  delete 'tabs/destroy/:id', to: "tabs#destroy", as: 'destroy_tab'

  get 'tabs/approve/:id', to: 'tabs#approve', as: 'approve_tab'

  get 'tabs/deny/:id', to: 'tabs#deny', as: 'deny_tab'

  get 'subtabs/approve/:id', to: 'subtabs#approve', as: 'approve_subtab'

  get 'subtabs/deny/:id', to: 'subtabs#deny', as: 'deny_subtab'
  
  delete 'subtabs/destroy/:id', to: "subtabs#destroy", as: 'destroy_subtab'
  
  get 'tabs/pending', as: 'pending_tabs'
  
  
  
  put 'feedbacks/update'
  
  post 'feedbacks/create', as: 'feedback'
  
  delete 'feedbacks/destroy/:id', to: "feedbacks#destroy", as: 'destroy_feedback'
  
  get 'users/:user_id/feedbacks/new', to: 'feedbacks#new', as: 'new_user_feedback'
  
  get 'posts/:post_id/feedbacks/new', to: 'feedbacks#new', as: 'new_post_feedback'
  
  get 'events/:event_id/feedbacks/new', to: 'feedbacks#new', as: 'new_event_feedback'
  
  get 'articles/:article_id/feedbacks/new', to: 'feedbacks#new', as: 'new_article_feedback'
  
  get 'comments/:comment_id/feedbacks/new', to: 'feedbacks#new', as: 'new_comment_feedback'
  
  get 'tabs/:tab_id/feedbacks/new', to: 'feedbacks#new', as: 'new_tab_feedback'
  
  post 'features/request_invite', as: 'request_invite'
  
  
  
  get 'features/switch_global', as: 'switch_global'
  
  get "features/page_jump/:tab_id", to: 'features#page_jump', as: 'page_jump'
  
  get "features/cherry_pick", to: 'features#cherry_pick', as: 'cherry_pick'
  
  get "features/un_cherry_pick", to: 'features#un_cherry_pick', as: 'un_cherry_pick'
  
  delete 'features/destroy/:id', to: 'features#destroy', as: 'destroy_feature'
  
  get 'features/insert_pre_feature_grid', as: 'insert_pre_feature_grid'
  
  post 'features/create', as: 'features'
  
  
  
  delete 'groups/destroy/:id', to: 'groups#destroy', as: 'destroy_group'
  
  put 'groups/remove_member'
  
  put 'groups/add_member'
  
  put 'groups/remove_zip'
  
  put 'groups/add_zip'
  
  
  
  delete 'codes/destroy/:id', to: 'codes#destroy', as: 'destroy_code'
  
  delete 'game_boards/destroy/:id', to: 'game_boards#destroy', as: 'destroy_board'
  
  get 'game_boards/reset/:id', to: 'game_boards#reset', as: 'reset'
  
  get 'game_boards', to: 'game_boards#index', as: 'boards'
  
  post 'game_boards/create', as: 'game_boards'
  
  post 'cards/create', as: 'cards'
  
  delete 'codes/clear', as: 'clear'
  
  get 'codes/code_data'
  
  
  
  get 'activities/:id/get_location', to: 'activities#get_location', as: 'get_location'
  
  get 'activities/unique_locations', as: 'unique_locations'
  
  get 'activities/unique_visits', as: 'unique_visits'
  
  delete 'activities/destroy_all', as: 'destroy_all_activities'
  
  
  
  put 'translations/update'
  
  delete 'translations/destroy/:id', to: 'translations#destroy', as: 'destroy_translation'
  
  get 'translations/requests', as: 'translation_reqs'
  
  
  
  get "search/search/:query", to: "search#search", as: "tagged"
  
  get "search/search", as: "search"
  
  
  
  get "pages/more", as: "more"
  
  get "pages/back", as: "back"
  
  
  
  post 'tips/create', as: 'tips_create'
  
  
  
  get 'tabs/:tab_id/polls/new', to: 'polls#new', as: 'new_tab_poll'
  
  get 'users/:user_id/polls/new', to: 'polls#new', as: 'new_user_poll'
  
  get 'polls/add_choice/:choice_num', to: 'polls#add_choice', as: 'add_choice'
  
  post 'polls/:poll_id/up_vote/:choice_id', to: 'polls#up_vote', as: 'up_vote_choice'
  
  post 'polls/:poll_id/down_vote/:choice_id', to: 'polls#down_vote', as: 'down_vote_choice'
  
  
  
  get 'tournaments/add_team/:team_num', to: 'tournaments#add_team', as: 'add_team'
  

  root 'welcome#index'
  
  resources :codes
  resources :posts
  resources :banners
  resources :loading_gifs
  resources :translations
  resources :sports_teams
  resources :activities
  resources :feedbacks
  resources :articles
  resources :groups
  resources :events
  resources :notes
  resources :polls
  resources :stats
  
  resources :game_boards do
    resources :cards
  end
  
  resources :folders do
    resources :messages
  end
  
  resources :tabs do
    resources :features
    resources :tournaments
    resources :sports_matches
    resources :subtabs do
      resources :features
    end
  end

  resources :users do
    resources :features
  end
  

end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :users
  has_many :zips
  has_many :codes
  has_many :prizes
  has_many :game_boards
  
  validate :only_one_default
  before_destroy :unassign_items
  
  def available_prizes(combo_type, user=nil, return_size=nil)
    prizes_by_combo = prizes.where(combo_type: combo_type)
    won_by_user = prizes_by_combo.where(user_id: user.id) if user
    available = prizes_by_combo.where(user_id: nil)
    if return_size
      return available.present? ? available.size : 0
    elsif user and won_by_user.empty? and available.present?
      return available
    else
      return nil
    end
  end
  
  def add_prizes(combo_type, amount)
    if combo_type and amount
      for i in 1..amount.to_i
        prizes.create(combo_type: combo_type)
      end
    end
  end
  
  def assemble(zip_list, admin_list)
    if zip_list
      zip_list.split(", ").each do |zip|
        _zip = Zip.find_by_zip_code(zip.to_i)
        if _zip
          _zip.update group_id: self.id
        end
      end
    end
    if admin_list
      admin_list.split(", ").each do |admin|
        _admin = User.find_by_name(admin)
        if _admin
          _admin.update group_id: self.id, admin: true
        end
      end
    end
  end
  
  def self.find_by_user(user)
    if user.zip_code.present?
      for group in self.all
        if group.zips.present? and group.zips.find_by_zip_code(user.zip_code)
          return group
        end
      end
    else
      return Group.default
    end
  end
  
  def self.default
    find_by_default true
  end
  
  def default_zips
  	if self.default
  		Zip.orphans
  	else
  		self.zips
  	end
  end
  
  private
  
  def only_one_default
    if self.default and Group.exists? default: true
      errors.add(:only_one_default, "There can only be one default group.")
    end
  end
  
  def unassign_items
    for zip in self.zips
      zip.update group_id: 0
    end
    for user in self.users
      user.update group_id: 0
    end
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def add_member
    if params[:user_name].present? and User.find_by_name(params[:user_name]) and \
      (User.find_by_name(params[:user_name]).group_id.nil? or User.find_by_name(params[:user_name]).group_id == 0)
      User.find_by_name(params[:user_name]).update group_id: params[:group_id], admin: true
      flash[:notice] = translate("Admin successfully added to group.")
      log_action("groups_add_member", params[:group_id])
    else
      flash[:error] = translate("User does not exist or already belongs to a group.")
      log_action("groups_add_member_fail", params[:group_id])
    end
    redirect_to :back
  end
  
  def remove_member
    admin = User.find_by_id(params[:user_id])
    if admin and admin.group_id.present? and admin.update group_id: 0
      flash[:notice] = translate("Member successfully removed from the group.")
      log_action("groups_remove_member", admin.id)
    else
      flash[:error] = translate("The member could not be removed.")
      log_action("groups_remove_member_fail", admin.id)
    end
    redirect_to :back
  end
  
  def add_zip
    if params[:zip_code].present? and Zip.find_by_zip_code(params[:zip_code]) and \
      (Zip.find_by_zip_code(params[:zip_code]).group_id.nil? or Zip.find_by_zip_code(params[:zip_code]).group_id == 0)
      Zip.find_by_zip_code(params[:zip_code]).update group_id: params[:group_id]
      flash[:notice] = translate("Zip code successfully added to group.")
      log_action("groups_add_zip", params[:group_id])
    else
      flash[:error] = translate("Zip code does not exist in database or already belongs to a group.")
      log_action("groups_add_zip_fail", params[:group_id])
    end
    redirect_to :back
  end
  
  def remove_zip
    zip = Zip.find_by_zip_code(params[:zip_code])
    if zip and zip.group_id.present? and zip.update group_id: 0
      flash[:notice] = translate("Zip code successfully removed from the group.")
      log_action("groups_remove_zip", zip.id)
    else
      flash[:error] = translate("The zip code could not be removed.")
      log_action("groups_remove_zip_fail", zip.id)
    end
    redirect_to :back
  end
  
  def edit
    @group = Group.find(params[:id])
    log_action("groups_edit")
  end
  
  def index
    @groups = Group.all
    @default = Group.default
    session[:group_id] = nil
    log_action("groups_index")
  end
  
  def new
    @group = Group.new
    log_action("groups_new")
  end
  
  def show
    @group = Group.find(params[:id])
    @group_shown = true if @group
    @zips = unless @group.default
              @group.zips
            else
              Zip.orphans
            end
    session[:group_id] = @group.id
    log_action("groups_show")
  end
  
  def create
    @group = Group.new(params[:group].permit(:max_prizes, :default))
    admin_list = params[:admin_list]; admin_list << ", #{current_user.name}"
    if @group.save
      @group.assemble(params[:zip_list], params[:admin_list])
      flash[:notice] = translate("Group saved successfully.")
      log_action("groups_create", @group.id)
      redirect_to groups_path
    elsif @group.errors.include? :only_one_default
      flash[:error] = translate(@group.errors[:only_one_default].first)
      log_action("groups_create_fail")
      redirect_to :back
    else
      flash[:error] = translate("Group failed to save.")
      log_action("groups_create_fail")
      redirect_to :back
    end
  end
  
  def update
    @group = Group.find(params[:id])
    if @group.add_prizes(params[:prize_combo_type], params[:prize_amount])
      log_action("groups_update", @group.id)
      flash[:notice] = translate("Group updated successfully.")
      redirect_to :back
    else
      flash[:error] = translate("Group failed to update.")
      log_action("groups_update_fail")
      redirect_to :back
    end
  end
  
  def destroy
    @group = Group.find_by_id(params[:id])
    if @group and @group.destroy
      flash[:notice] = translate("Group deleted successfully.")
      log_action("groups_destroy")
      redirect_to groups_path
    else
      flash[:error] = translate "There was a problem deleting the group."
      log_action("groups_destroy_fail")
      redirect_to :back
    end
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_card.html.erb
<!-- groups -->

<div id="card">
	<%= link_to translate("Edit prizes"), edit_group_path(group), class: :top_right_link %>
	<%= link_to translate("Delete"), destroy_group_path(group), class: :top_left_link, method: :delete,
		data: { confirm: translate('Are you sure you want to delete this group?') } %>
		
	<div align="center">
		<%= render "groups/name_header", group: group %>
		<% if group.users.present? %>
			<p><%= "Admins: " %>
				<% for admin in group.users %>
					<%= link_to admin.name.capitalize, groups_remove_member_path(user_id: admin.id), method: :put,
						data: { confirm: translate('Are you sure you want to remove this member from the group?') } %><%= \
					", " if admin != group.users.last and group.users.size > 1 %>
				<% end %>
			</p>
		<% end %>
		<% if group.default_zips.present? %>
			<p><%= "Zip codes: " %>
				<% for zip in group.default_zips %>
					<%= link_to zip.zip_code.to_s, groups_remove_zip_path(zip_code: zip.zip_code), method: :put,
						data: { confirm: translate('Are you sure you want to remove this zip code from the group?') } %><%= \
						", " if zip != group.default_zips.last and group.default_zips.size > 1 %>
				<% end %>
			</p>
		<% end %>
	</div>
	<%= render "groups/forms" if @group %>
</div>

app/views/groups/_forms.html.erb
<!-- groups -->

<p>
	<%= form_tag groups_add_member_path, method: :put do %>
		<%= hidden_field_tag :group_id, params[:id] %>
		<div class="input-group">
			<%= text_field_tag :user_name, nil,
				placeholder: translate("Add a new admin to the group by name"), class: "form-control" %>
			<span class="input-group-btn">
				<button class="btn btn-default" type="submit">
					<i class="glyphicon glyphicon-plus-sign"></i>
				</button>
			</span>
		</div><!-- /input-group -->
	<% end %>
</p>

<% unless @group.default %>
	<%= form_tag groups_add_zip_path, method: :put do %>
		<%= hidden_field_tag :group_id, params[:id] %>
		<div class="input-group">
			<%= text_field_tag :zip_code, nil,
				placeholder: translate("Add a new zip code to the group"), class: "form-control" %>
			<span class="input-group-btn">
				<button class="btn btn-default" type="submit">
					<i class="glyphicon glyphicon-plus-sign"></i>
				</button>
			</span>
		</div><!-- /input-group -->
	<% end %>
<% end %>

app/views/groups/_name_header.html.erb
<!-- groups -->

<% if group.default %>
	<p><%= link_to translate("Default Group"), group_path(group) %></p>
<% elsif @group_shown %>
	<p>
		<strong><%= "Group #{group.id}" %></strong>
	</p>
<% else %>
	<p><%= link_to "Group #{group.id}", group_path(group) %></p>
<% end %>

app/views/groups/edit.html.erb
<!-- groups -->

<% if master? %>
	<%= form_for @group do |f| %>
		<div id="card">
			<div align="center">
				<p>
					First corner: <%= @group.available_prizes("first_corner", nil, :size) %>,
					First center: <%= @group.available_prizes("first_center", nil, :size) %>,
					Four corners: <%= @group.available_prizes("four_corners", nil, :size) %>
				</p>
				
				<p>
					Line of four: <%= @group.available_prizes("line_of_four", nil, :size) %>,
					Full board: <%= @group.available_prizes("full_board", nil, :size) %>
				</p>
				
				<p>
					<%= select_tag :prize_combo_type, options_for_select([[translate("Add prizes to the group"), nil],
						[translate("First corner"), "first_corner"], [translate("First center"), "first_center"],
						[translate("Four corners"), "four_corners"], [translate("Line of four"), "line_of_four"],
						[translate("Full board"), "full_board"]]), class: "form-control" %>
				</p>
				
				<p>
					<%= text_field_tag :prize_amount, nil, placeholder: translate("Amount to add"), class: "form-control" %>
				</p>
				
				<p>
					<%= f.submit translate("Update"), class: "btn btn-default btn-lg btn-block" %>
				</p>
			</div>
		</div>
	<% end %>
<% end %>
</br>

app/views/groups/index.html.erb
<!-- groups -->

<% if master? %>
	<div id="large_button">
		<%= link_to "Create a group", new_group_path,
			class: "btn btn-default btn-lg btn-block" %>
	</div></br>
	
	<% for group in @groups %>
		<%= render "groups/card", group: group %>
	<% end %>

	<% if @groups.empty? %>
		<div id="card">
			<div align="center">
				<%= translate("There aren't any groups yet.") %>
			</div>
		</div>
	<% end %>
<% end %>

app/views/groups/new.html.erb
<!-- groups -->

<% if master? %>
	<div id="card">
		<%= form_for @group do |f| %>
			<p>
				<%= text_field_tag :zip_list, nil,
					placeholder: translate("Zip codes for this group (comma separated ', ')"),
					class: "form-control" %>
			</p>
			<p>
				<%= text_field_tag :admin_list, nil,
					placeholder: translate("Admins for this group (names, comma separated ', ')"),
					class: "form-control" %>
			</p>
			<p>
				<%= f.text_field :max_prizes,
					placeholder: translate("Maximum amount of wins available"),
					class: "form-control" %>
			</p>
			<p class="form-control">
				<%= f.label translate("Default") %>
				<%= f.check_box :default %>	
			</p>
			<p>
				<%= f.submit translate("Create"), class: "btn btn-default btn-lg btn-block" %>
			</p>
		<% end %>
	</div>
<% end %>

app/views/groups/show.html.erb
<!-- groups -->

<% if master? %>
	<%= render "groups/card", group: @group %>
	
	<div id="card">
		<%= render "admin/admin_buttons" %>
	</div>
<% end %>